### ISSUE TITLE
setUpHostel - Document the function using comment 

### ISSUE THREAD

**Issue by ADIIS007** [ADIIS007/namma-guest-spring-boot#7]
![image](https://github.com/user-attachments/assets/f8e2259e-f83a-47f4-8b4e-49536ed6222d)
Like this sample

**Comment by SasidharanVijayan** [comment]
Is anyone currently working on this? If not, I'd like to take it up!

**Comment by SasidharanVijayan** [comment]
could you confirm the process for submitting changes? Should I create a branch or submit code snippets here?
